spring:
  application:
    name: subing

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration: {}  # Phase 2: 소셜 로그인

# JWT 기본값
jwt:
  refresh-token-validity: 604800000  # 7일
